name: Deploy to hosting

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: 
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: o2switch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd "$DEPLOY_PATH"
            git pull
            composer install --no-dev --optimize-autoloader
            npm i 
            npm run build
            php bin/console cache:clear --env=prod
            php bin/console cache:warmup --env=prod
